apiVersion: v1
kind: Service
metadata:
  name: projetogeral-front
  labels:
    app: projetogeral-front
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32500
  selector:
    app: projetogeral-front
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: projetogeral-front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: projetogeral-front
    spec:
      containers:
        - name: projetogeral-front
          image: "127.0.0.1:30400/projetogeral-front:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
